// The three preloaded sample documents shown in the "try a sample" row. Files
// live in public/samples/ and are generated by scripts/generate-samples.ts.
// Clicking one fetches the file and runs it through the normal /api/extract path
// — so a cold visitor with no document of their own still sees the full flow.
export interface SampleDoc {
  id: string;
  /** Public path under /public. */
  path: string;
  media: "application/pdf" | "image/png";
  /** Short label shown on the chip. */
  label: string;
  /** One-line description of what makes this sample interesting. */
  blurb: string;
}

export const SAMPLES: SampleDoc[] = [
  {
    id: "northwind-services",
    path: "/samples/northwind-services-invoice.pdf",
    media: "application/pdf",
    label: "Services invoice (PDF)",
    blurb: "Clean multi-line services invoice — subtotal, tax, and total all reconcile.",
  },
  {
    id: "orbit-supply",
    path: "/samples/orbit-supply-invoice.pdf",
    media: "application/pdf",
    label: "Product invoice (PDF)",
    blurb: "Itemized product order with quantities and unit prices.",
  },
  {
    id: "corner-cafe",
    path: "/samples/corner-cafe-receipt.png",
    media: "image/png",
    label: "Cafe receipt (image)",
    blurb: "A small photographed-style receipt image — exercises the vision path.",
  },
];
